import { Panel, PanelHeader, PanelTitle } from "@/components/common/Card";
import { useAnalysis } from "@/context/AnalysisContext";
import { ASSUMPTIONS as SEED_ASSUMPTIONS } from "@/data/analysis";
import { fmtCurrency } from "@/lib/format";
import { Plus, Pencil } from "lucide-react";
import { useState } from "react";

const CATEGORIES = ["Add-Backs", "Debt Adjustments", "Other", "Working Capital"];

export function AssumptionsTab() {
  const { inputs, result } = useAnalysis();

  // Use live assumptions if analysis has run, else seed data
  const assumptions = result?.assumptions?.length ? result.assumptions : SEED_ASSUMPTIONS;

  // Bridge from context
  const ebitda = inputs.ebitda * 1e6;
  const netDebt = inputs.netDebt * 1e6; // negative = net cash

  // Compute add-backs total
  const addBacks = assumptions
    .filter((a) => a.category === "Add-Backs")
    .reduce((sum, a) => sum + a.value * 1e6, 0);
  const adjustedEbitda = ebitda + addBacks;

  const medianEE = result?.stats.medianEvEbitda ?? 28;
  const impliedEv = adjustedEbitda * medianEE;

  // Bridge rows — use live data if available, otherwise compute from inputs
  const bridge = result?.bridge?.length
    ? result.bridge
    : [
        { label: "Enterprise Value (Base)", value: impliedEv / 1e6 },
        { label: "(+) Cash & equivalents", value: inputs.netDebt < 0 ? Math.abs(inputs.netDebt) : 0 },
        { label: "(−) Total debt", value: inputs.netDebt > 0 ? inputs.netDebt : 0 },
        { label: "(−) Capitalized leases", value: 12.5 },
        { label: "(−) Minority interest", value: 4.8 },
        { label: "(−) Earnout liability", value: 9.2 },
      ];

  const equityValue = bridge.reduce((sum, r, i) => {
    if (i === 0) return r.value;
    return sum + r.value;
  }, 0);

  const [localAssumptions, setLocalAssumptions] = useState(assumptions);

  function updateValue(id: string, delta: number) {
    setLocalAssumptions((prev) =>
      prev.map((a) => (a.id === id ? { ...a, value: +(a.value + delta).toFixed(2) } : a)),
    );
  }

  return (
    <div className="grid grid-cols-12 gap-3">
      <Panel className="col-span-12 lg:col-span-8">
        <PanelHeader>
          <PanelTitle>Adjustments & Assumptions</PanelTitle>
          <div className="flex items-center gap-2">
            {result && (
              <span className="rounded border border-positive/30 bg-positive/10 px-1.5 py-0.5 text-[9px] font-medium uppercase tracking-wider text-positive">
                Live
              </span>
            )}
            <button className="flex items-center gap-1 rounded border border-border bg-surface-2 px-2 py-0.5 text-[10px] text-foreground hover:border-border-strong">
              <Plus className="h-3 w-3" /> Add line
            </button>
          </div>
        </PanelHeader>

        <div className="divide-y divide-border">
          {CATEGORIES.map((cat) => {
            const items = localAssumptions.filter((a) => a.category === cat);
            if (!items.length) return null;
            return (
              <div key={cat} className="px-4 py-3">
                <div className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  {cat}
                </div>
                <table className="w-full text-[12px]">
                  <tbody>
                    {items.map((a) => (
                      <tr key={a.id} className="group">
                        <td className="py-1.5 text-foreground">{a.label}</td>
                        <td className="py-1.5 text-[11px] text-muted-foreground">{a.note}</td>
                        <td className="w-28 py-1.5 text-right">
                          <span className="num text-foreground">
                            {a.value > 0 ? "+" : ""}
                            {a.value.toFixed(1)}
                          </span>
                          <span className="ml-1 text-[10px] text-muted-foreground">{a.unit}</span>
                        </td>
                        <td className="w-8 py-1.5 text-right">
                          <button
                            onClick={() => updateValue(a.id, 0)}
                            className="opacity-0 transition-opacity group-hover:opacity-100 text-muted-foreground hover:text-foreground"
                          >
                            <Pencil className="h-3 w-3" />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            );
          })}
        </div>

        <div className="border-t border-border px-4 py-2.5 text-[10px] text-muted-foreground">
          {result ? "Assumptions generated by analysis · Click pencil icon to edit" : "Seed assumptions · Run analysis to refresh from live data"}
        </div>
      </Panel>

      <Panel className="col-span-12 lg:col-span-4">
        <PanelHeader>
          <PanelTitle>Bridge to Equity Value</PanelTitle>
        </PanelHeader>
        <div className="space-y-2 px-4 py-3 text-[12px]">
          {bridge.map((r, i) => {
            const isFirst = i === 0;
            const isPositive = !isFirst && r.value > 0;
            const toneClass = isFirst
              ? "text-foreground"
              : isPositive
                ? "text-positive"
                : "text-muted-foreground";
            return (
              <div
                key={i}
                className="flex items-center justify-between border-b border-border/40 pb-1.5"
              >
                <span className={isFirst ? "text-foreground" : "text-muted-foreground"}>
                  {r.label}
                </span>
                <span className={`num ${toneClass}`}>${r.value.toFixed(1)}M</span>
              </div>
            );
          })}

          <div className="flex items-center justify-between rounded border border-accent/40 bg-accent/10 px-2.5 py-2">
            <span className="text-[11px] font-semibold uppercase tracking-wider text-foreground">
              Equity Value
            </span>
            <span className="num text-[14px] font-semibold text-foreground">
              {fmtCurrency(equityValue * 1e6)}
            </span>
          </div>

          <div className="pt-1 text-[10px] text-muted-foreground">
            Implied EV at {medianEE.toFixed(1)}x LTM EBITDA
            {inputs.netDebt < 0
              ? ` · Net cash $${Math.abs(inputs.netDebt)}M`
              : ` · Net debt $${inputs.netDebt}M`}
          </div>
        </div>
      </Panel>
    </div>
  );
}
